- hosts: host
  gather_facts: no
  tasks:
  - name: Create templates
    template: 
      src: "{{lookup('env','PWD')}}/templates/host.j2"
      dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_vlan.cfg"

